In [3]:
# 1) np.array()
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x
# array([[1, 2, 3],
#        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 2) np.zeros()
np.zeros(5)
# array([ 0.,  0.,  0.,  0.,  0.])

s = (2,2)
np.zeros(s)
# array([[0., 0.],
#        [0., 0.]])

array([[0., 0.],
       [0., 0.]])

In [7]:
# 3) np.ones()
np.ones(5)
#array([1., 1., 1., 1., 1.])

s = (2,2)
np.ones(s)
# array([[1., 1.],
#        [1., 1.]])

array([[1., 1.],
       [1., 1.]])

In [9]:
# 4) np.full()
np.full((2, 2), 10)
# array([[10, 10],
#        [10, 10]])
np.full((2, 2), [1, 2])
# array([[1, 2],
#        [1, 2]])

array([[10, 10],
       [10, 10]])

In [14]:
# 5) np.ravel()
x = np.array([[1, 2, 3], [4, 5, 6]])
res=np.ravel(x)
print(res)  # [1 2 3 4 5 6]

np.ravel(x, order='F') # 행별로 평탄화
# array([1, 4, 2, 5, 3, 6])

x.T
# array([[1, 4],
#        [2, 5],
#        [3, 6]])
np.ravel(x.T)
# array([1, 4, 2, 5, 3, 6])
np.ravel(x.T, order='A')
# array([1, 2, 3, 4, 5, 6])

[1 2 3 4 5 6]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
# 6) np.dot()
# dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
a = [[1, 0], 
     [0, 1]]
b = [[4, 1], 
     [2, 2]]
np.dot(a, b)
# array([[4, 1],  [1*4 + 0*2, 1*1 + 0*2]
#        [2, 2]]) [0*4 + 1*2, 0*1 + 1*2]

array([[4, 1],
       [2, 2]])

In [22]:
# 7) np.concatenate()
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
np.concatenate((a, b), axis=None)
# array([1, 2, 3, 4, 5, 6])

print(b.T)
# [[5]
#  [6]]
np.concatenate((a, b.T), axis=1)
# array([[1, 2, 5],
#        [3, 4, 6]])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 8) np.vstack()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))
# array([[1, 2, 3],
#        [4, 5, 6]])

a = np.array([[1], 
              [2], 
              [3]])
b = np.array([[4], 
              [5], 
              [6]])
np.vstack((a,b))
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5],
#        [6]])

In [ ]:
# 9) np.where()
a = np.arange(10)
# a = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a < 5, a, 10*a) # 5보다 작은 것은 그대로 나오게 하고 그 외는 10을 곱해서 나오게 하라
# array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [23]:
# 10) np.std() 표준 편차 계산
a = np.array([[1, 2], [3, 4]])
np.std(a)
# 1.118033988749895

1.118033988749895

In [25]:
# 11) np.max() 최댓값 반환
a=([[0, 1],
    [2, 3],
    [4, 5]])
np.max(a)    # 5
np.max(a, axis=0) # [4, 5]
np.max(a, axis=1) # [1, 3, 5]

array([1, 3, 5])

In [ ]:
# 12) np.argmax() 최대값의 인덱스 반환
a=([[10, 11, 12],
    [13, 14, 15]])
np.argmax(a) # 15= a[1,2] = 평탄화하면 a[5] -> 5
np.argmax(a, axis=0) # 세로로 했을때
# [10,13] 중에 [13]이니까 인덱스 [1] = array [1,1,1]
np.argmax(a, axis=1) # 가로로 했을 때
# [10,11,12] 중에 [12] 니까 [2]
# [13,14,15] 중에 [15] 니까 [2] = array [2,2]

In [ ]:
# 13) np.eye()
np.eye(2, dtype=int)
# array([[1, 0],
#        [0, 1]])

In [28]:
# 14) np.arange()
np.arange(3)
# array([0, 1, 2])
np.arange(3,7)
# array([3, 4, 5, 6])
np.arange(3,7,2)
# array([3, 5])

array([3, 5])

In [29]:
# 15) np.linspace()
np.linspace(2.0, 3.0, num=5)
# 2~3 까지를 5개로 나눠서 출력해라
# array([2.  , 2.25, 2.5 , 2.75, 3.  ])

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [30]:
# 16) np.reshape()
a = np.arange(6).reshape((3, 2))
#np.arange(6)=[0,1,2,3,4,5] 3열 2행으로 분류해라
a
# array([[0, 1],
#        [2, 3],
#        [4, 5]])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
# 17) np.transpose() 전환
a=([[1, 2],
    [3, 4]])
np.transpose(a)
# array([[1, 3],
#        [2, 4]])
a=([1, 2, 3, 4])
np.transpose(a) # 안 바뀜
# array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
# 18) np.cross() 두 배열의 외적계산
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)
# array([-3,  6, -3]) 
[2*6-3*5, 3*4-1*6,1*5-2*4]

In [36]:
# 19) np.split()
x = np.arange(9.0) #[0. 1. 2. 3. 4. 5. 6. 7. 8.]
np.split(x, 3)
# [array([0., 1., 2.]), 
#  array([3., 4., 5.]), 
#  array([6., 7., 8.])]

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [42]:
# 20) np.hstack() 배열을 수평으로 쌓음
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))
# array([1, 2, 3, 4, 5, 6])

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))
# array([[1, 4],
#        [2, 5],
#        [3, 6]])


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 21) np.mean() 평균 계산
a = np.array([[1, 2], 
              [3, 4]])
np.mean(a) # 2.5

np.mean(a, axis=0)
# array([2., 3.])

np.mean(a, axis=1)
# array([1.5, 3.5])

In [ ]:
# 22) np.min() 최대값 인덱스
a=([[0, 1],
    [2, 3]])
np.min(a)  # 0
np.min(a, axis=0)  # 세로로 봤을 때니까
# [0,2] 중에 [0] [1,3]중에 [1] = array[0,1]
np.min(a, axis=1) # 가로로 봤을 때
# [0,1] 중에 [0] [2,3] 증에 [2] = array [0,2]

In [ ]:
# 23) np.argmin() 최소값 인덱스
a = ([[10, 11, 12],
       [13, 14, 15]])
np.argmin(a) # 0 = a[0,0]

np.argmin(a, axis=0)
# array([0, 0, 0]) [10,13] 중에 [0] 인덱스

np.argmin(a, axis=1)
# array([0, 0]) [10,11,12] 중에 [10] [0] 인덱스

In [4]:
# 24) np.unique() 중복값 제거
import numpy as np
np.unique([1, 3, 2, 3, 1, 3])
# array([1, 2, 3]) 정렬까지 해준다.

a = np.array([[2, 3, 4], [1, 0, 0], [1, 0, 0]])
np.unique(a,axis=0)
# array([[1, 0, 0],
#        [2, 3, 4]])  중복값 제거 및 정렬까지

array([1, 2, 3])